
# registry.cn-hangzhou.aliyuncs.com/lpx03/xtrabackup:base-glib-2.28
FROM registry.cn-hangzhou.aliyuncs.com/lpx03/rockylinux:8.9.20231119

# # 替换 Rocky Linux 源为南大镜像
# RUN sed -e 's|^mirrorlist=|#mirrorlist=|g' \
#         -e 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=https://mirror.nju.edu.cn/rocky|g' \
#         -i.bak \
#         /etc/yum.repos.d/Rocky-*.repo

# 安装 EPEL 并替换为南大镜像: 包含了powerTools,要不然得单独加repo
RUN yum install -y epel-release 
#    && \
#    sed -e 's!^metalink=!#metalink=!g' \
#        -e 's!^#baseurl=!baseurl=!g' \
#        -e 's!https\?://download\.fedoraproject\.org/pub/epel!https://mirror.nju.edu.cn/epel!g' \
#        -e 's!https\?://download\.example/pub/epel!https://mirror.nju.edu.cn/epel!g' \
#        -i /etc/yum.repos.d/epel.repo /etc/yum.repos.d/epel-testing.repo

# 安装编译依赖
RUN yum install -y procps-ng-devel --enablerepo=powertools && \
    yum install -y \
        autoconf \
        automake \
        bison \
        cmake \
        cyrus-sasl-devel \
        file \
        gcc-c++ \
        git \
        libaio \
        libaio-devel \
        libarchive \
        libcurl-devel \
        libev-devel \
        libgcrypt-devel \
        libgpg-error-devel \
        libicu-devel \
        libtool \
        libtirpc-devel \
        libudev-devel \
        libxml2-devel \
        libzstd-devel \
        lz4-devel \
        make \
        ncurses-devel \
        numactl-devel \
        openldap-devel \
        openssl-devel \
        patch \
        patchelf \
        protobuf-compiler \
        readline-devel \
        vim-common \
        zlib-devel \
        zstd \
        gcc-toolset-12-gcc \
        gcc-toolset-12-gcc-c++ \
        gcc-toolset-12-binutils \
        gcc-toolset-12-annobin-annocheck \
        gcc-toolset-12-annobin-plugin-gcc && \
    yum clean all && \
    rm -rf /var/cache/yum
